### ISSUE TITLE
Kanboard-Project Setup

### ISSUE THREAD

**Issue by AlierPM** [AlierPM/space-travelers--hub#23]
Were are a group of 3 members 

@AlierPM   @Loltolo-Lesapiti    @Bantealem 
Here is the link to our Project: [React Group Project](https://github.com/AlierPM/space-travelers--hub/projects/1?query=is%3Aopen+sort%3Aupdated-desc)

**Comment by Omar-Muhamad** [comment]
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] For a team with three people number of kanban cards should be equal to 24, not only 22. Please add the missing 2 kanban cards.

![image](https://user-images.githubusercontent.com/68796232/195085442-bfccf6c0-e658-42a3-9fa8-3df5b5e639f2.png)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AlierPM** [comment]
Thanks @Omar-Muhamad! Considered done!

**Comment by Munsa1** [comment]
Hi @Omar-Muhamad, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
